package model.vo.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 22:14:22 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void DeleteAllEmps();
}
