package model.vo;

import model.vo.common.AppModule;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 22:10:14 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    public void DeleteAllEmps(){
        
       ViewObject vo =  this.findViewObject("Emp1");
       vo.executeQuery();
       
    }

    /**
     * Container's getter for DeptView1.
     * @return DeptView1
     */
    public ViewObjectImpl getDeptView1() {
        return (ViewObjectImpl)findViewObject("DeptView1");
    }

    /**
     * Container's getter for EmpView1.
     * @return EmpView1
     */
    public ViewObjectImpl getEmpView1() {
        return (ViewObjectImpl)findViewObject("EmpView1");
    }

    /**
     * Container's getter for SalgradeView1.
     * @return SalgradeView1
     */
    public ViewObjectImpl getSalgradeView1() {
        return (ViewObjectImpl)findViewObject("SalgradeView1");
    }

    /**
     * Container's getter for EmpView2.
     * @return EmpView2
     */
    public ViewObjectImpl getEmpView2() {
        return (ViewObjectImpl)findViewObject("EmpView2");
    }

    /**
     * Container's getter for HighlyPaidEmployees1.
     * @return HighlyPaidEmployees1
     */
    public ViewObjectImpl getHighlyPaidEmployees1() {
        return (ViewObjectImpl)findViewObject("HighlyPaidEmployees1");
    }

    /**
     * Container's getter for EmpTranslated1.
     * @return EmpTranslated1
     */
    public ViewObjectImpl getEmpTranslated1() {
        return (ViewObjectImpl)findViewObject("EmpTranslated1");
    }

    /**
     * Container's getter for SalgradeView2.
     * @return SalgradeView2
     */
    public ViewObjectImpl getSalgradeView2() {
        return (ViewObjectImpl)findViewObject("SalgradeView2");
    }

    /**
     * Container's getter for SalgradeView3.
     * @return SalgradeView3
     */
    public ViewObjectImpl getSalgradeView3() {
        return (ViewObjectImpl)findViewObject("SalgradeView3");
    }

    /**
     * Container's getter for FkDeptnoLink1.
     * @return FkDeptnoLink1
     */
    public ViewLinkImpl getFkDeptnoLink1() {
        return (ViewLinkImpl)findViewLink("FkDeptnoLink1");
    }

    /**
     * Container's getter for SalgradeToEmployees.
     * @return SalgradeToEmployees
     */
    public ViewLinkImpl getSalgradeToEmployees() {
        return (ViewLinkImpl)findViewLink("SalgradeToEmployees");
    }
}
